### ISSUE TITLE
Ignore non-comment lines

### ISSUE THREAD

**Issue by jmcerrejon** [amannn/atom-format-javascript-comment#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [format-javascript-comment](https://github.com/amannn/atom-format-javascript-comment) package 0.2.4

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /Users/ulysess/.atom/packages/format-javascript-comment/lib/formatCommentLines.js:33

TypeError: Cannot read property '0' of null
    at formatCommentLines (/packages/format-javascript-comment/lib/formatCommentLines.js:33:41)
    at /packages/format-javascript-comment/lib/index.js:10:17
    at Array.forEach (native)
    at _formatComment (/packages/format-javascript-comment/lib/index.js:8:16)
    at /packages/format-javascript-comment/lib/index.js:20:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:04.2.0 command-palette:toggle (input.hidden-input)
     -0:01.9.0 core:confirm (input.hidden-input)
     -0:01.9.0 format-comment (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-jade 0.3.0 
auto-update-packages 1.0.1 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.8 
format-javascript-comment 0.2.4 
hyperclick 0.1.2 
intentions 1.1.2 
jshint 1.8.6 
language-blade 0.32.0 
linter 2.2.0 
linter-jshint 3.1.5 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.2 
operator-mono 0.10.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
project-manager 3.3.5 
symbols-list 2.4.1 
ti-create 0.30.0 
titanium-alloy 0.14.4 
titanium-build 0.8.1 
titanium-language-javascript 0.48.0 
```

**Comment by amannn** [comment]
@jmcerrejon Thanks for the bug report! This looks to me like you were trying to format a selection where the first line wasn't a comment – is that true?

**Comment by jmcerrejon** [comment]
You are right, man!. Thks.

**Comment by amannn** [comment]
Probably I should provide a better error/info message or ignore those lines. The current behaviour can be confusing.
